defmodule BlockchainTest do
  use ExUnit.Case
  use EthCommonTest.Harness

  alias Blockchain.{Blocktree, Account, Transaction}
  alias MerklePatriciaTree.Trie
  alias Blockchain.Account.Storage
  alias Block.Header

  doctest Blockchain

  @ethereum_common_tests_path "/../../ethereum_common_tests/BlockchainTests/"

  @tests [
    "GeneralStateTests/stAttackTest/ContractCreationSpam_d0g0v0.json",
    "GeneralStateTests/stAttackTest/CrashingTransaction_d0g0v0.json",
    "GeneralStateTests/stCallCodes/call_OOG_additionalGasCosts1_d0g0v0.json",
    "GeneralStateTests/stCallCodes/call_OOG_additionalGasCosts2_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcall_00_OOGE_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcall_00_OOGE_valueTransfer_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcall_00_OOGE_valueTransfer_d1g0v0.json",
    "GeneralStateTests/stCallCodes/callcall_00_SuicideEnd_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcall_00_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcall_000_OOGE_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcall_000_OOGMAfter_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcall_000_OOGMBefore_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcall_000_SuicideEnd_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcall_000_SuicideMiddle_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcall_000_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcall_ABCB_RECURSIVE_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcallcode_001_OOGE_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcallcode_001_OOGMAfter_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcallcode_001_OOGMBefore_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcallcode_001_SuicideEnd_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcallcode_001_SuicideMiddle_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcallcode_001_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcallcode_ABCB_RECURSIVE_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcode_01_OOGE_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcode_01_SuicideEnd_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcode_01_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcodecall_010_OOGE_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcodecall_010_OOGMAfter_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcodecall_010_OOGMBefore_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcodecall_010_SuicideEnd_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcodecall_010_SuicideMiddle_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcodecall_010_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcodecall_ABCB_RECURSIVE_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcodecallcode_011_OOGE_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcodecallcode_011_OOGMAfter_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcodecallcode_011_OOGMBefore_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcodecallcode_011_SuicideEnd_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcodecallcode_011_SuicideMiddle_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcodecallcode_011_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcallcodecallcode_ABCB_RECURSIVE_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodeDynamicCode2SelfCall_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodeDynamicCode_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodeEmptycontract_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodeInInitcodeToEmptyContract_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodeInInitcodeToExisContractWithVTransferNEMoney_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodeInInitcodeToExistingContractWithValueTransfer_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodeInInitcodeToExistingContract_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcode_checkPC_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecall_10_OOGE_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecall_10_SuicideEnd_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecall_10_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcall_100_OOGE_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcall_100_OOGMAfter_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcall_100_OOGMBefore_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcall_100_SuicideEnd_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcall_100_SuicideMiddle_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcall_100_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcall_ABCB_RECURSIVE_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcallcode_101_OOGE_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcallcode_101_OOGMAfter_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcallcode_101_OOGMBefore_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcallcode_101_SuicideEnd_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcallcode_101_SuicideMiddle_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcallcode_101_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcallcode_ABCB_RECURSIVE_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcode_11_OOGE_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcode_11_SuicideEnd_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcode_11_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcodecall_110_OOGE_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcodecall_110_OOGMAfter_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcodecall_110_OOGMBefore_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcodecall_110_SuicideEnd_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcodecall_110_SuicideMiddle_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcodecall_110_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcodecall_ABCB_RECURSIVE_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcodecallcode_111_OOGE_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcodecallcode_111_OOGMAfter_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcodecallcode_111_OOGMBefore_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcodecallcode_111_SuicideEnd_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcodecallcode_111_SuicideMiddle_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcodecallcode_111_d0g0v0.json",
    "GeneralStateTests/stCallCodes/callcodecallcodecallcode_ABCB_RECURSIVE_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/Call1024BalanceTooLow_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/Call1024OOG_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/Call1024PreCalls_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/CallLoseGasOOG_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/CallRecursiveBombPreCall_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/Callcode1024BalanceTooLow_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/Callcode1024OOG_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/CallcodeLoseGasOOG_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/callOutput1_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/callOutput2_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/callOutput3Fail_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/callOutput3_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/callOutput3partialFail_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/callOutput3partial_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/callWithHighValueAndGasOOG_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/callWithHighValueAndOOGatTxLevel_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/callWithHighValueOOGinCall_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/callWithHighValue_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/callcodeOutput1_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/callcodeOutput2_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/callcodeOutput3Fail_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/callcodeOutput3_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/callcodeOutput3partialFail_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/callcodeOutput3partial_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/callcodeWithHighValueAndGasOOG_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/callcodeWithHighValue_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/createFailBalanceTooLow_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/createInitFailBadJumpDestination_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/createInitFailStackSizeLargerThan1024_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/createInitFailStackUnderflow_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/createInitFailUndefinedInstruction_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/createInitFail_OOGduringInit_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/createInitOOGforCREATE_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/createJS_ExampleContract_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/createJS_NoCollision_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/createNameRegistratorPerTxsNotEnoughGas_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/createNameRegistratorPerTxs_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/createNameRegistratorPreStore1NotEnoughGas_d0g0v0.json",
    "GeneralStateTests/stCallCreateCallCodeTest/createNameRegistratorendowmentTooHigh_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcallcallcode_001_OOGE_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcallcallcode_001_OOGMAfter_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcallcallcode_001_OOGMBefore_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcallcallcode_001_SuicideEnd_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcallcallcode_001_SuicideMiddle_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcallcallcode_001_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcallcallcode_ABCB_RECURSIVE_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcallcode_01_OOGE_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcallcode_01_SuicideEnd_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcallcode_01_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcallcodecall_010_OOGE_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcallcodecall_010_OOGMAfter_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcallcodecall_010_OOGMBefore_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcallcodecall_010_SuicideEnd_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcallcodecall_010_SuicideMiddle_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcallcodecall_010_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcallcodecall_ABCB_RECURSIVE_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcallcodecallcode_011_OOGE_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcallcodecallcode_011_OOGMAfter_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcallcodecallcode_011_OOGMBefore_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcallcodecallcode_011_SuicideEnd_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcallcodecallcode_011_SuicideMiddle_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcallcodecallcode_011_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcallcodecallcode_ABCB_RECURSIVE_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecall_10_OOGE_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecall_10_SuicideEnd_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecall_10_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcall_100_OOGE_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcall_100_OOGMBefore_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcall_100_SuicideEnd_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcall_100_SuicideMiddle_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcall_100_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcall_ABCB_RECURSIVE_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcallcode_101_OOGE_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcallcode_101_OOGMAfter_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcallcode_101_OOGMBefore_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcallcode_101_SuicideEnd_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcallcode_101_SuicideMiddle_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcallcode_101_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcallcode_ABCB_RECURSIVE_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcode_11_OOGE_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcode_11_SuicideEnd_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcode_11_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcodecall_110_OOGE_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcodecall_110_OOGMAfter_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcodecall_110_OOGMBefore_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcodecall_110_SuicideEnd_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcodecall_110_SuicideMiddle_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcodecall_110_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcodecall_ABCB_RECURSIVE_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcodecallcode_111_OOGE_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcodecallcode_111_OOGMBefore_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcodecallcode_111_SuicideEnd_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcodecallcode_111_SuicideMiddle_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcodecallcode_111_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesCallCodeHomestead/callcodecallcodecallcode_ABCB_RECURSIVE_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesHomestead/callcallcallcode_001_OOGMAfter_d0g0v0.json",
    "GeneralStateTests/stCallDelegateCodesHomestead/callcallcodecall_010_OOGMAfter_d0g0v0.json",
    "GeneralStateTests/stChangedEIP150/callcallcallcode_001_OOGMAfter_1_d0g0v0.json",
    "GeneralStateTests/stChangedEIP150/callcallcallcode_001_OOGMAfter_2_d0g0v0.json",
    "GeneralStateTests/stChangedEIP150/callcodecallcall_100_OOGMAfter_1_d0g0v0.json",
    "GeneralStateTests/stChangedEIP150/contractCreationMakeCallThatAskMoreGasThenTransactionProvided_d0g0v0.json",
    "GeneralStateTests/stChangedEIP150/contractCreationMakeCallThatAskMoreGasThenTransactionProvided_d0g1v0.json",
    "GeneralStateTests/stCodeSizeLimit/codesizeOOGInvalidSize_d0g0v0.json",
    "GeneralStateTests/stCodeSizeLimit/codesizeValid_d0g0v0.json",
    "GeneralStateTests/stCreateTest/CREATE_AcreateB_BSuicide_BStore_d0g0v0.json",
    "GeneralStateTests/stCreateTest/CREATE_ContractRETURNBigOffset_d0g0v0.json",
    "GeneralStateTests/stCreateTest/CREATE_ContractRETURNBigOffset_d1g0v0.json",
    "GeneralStateTests/stCreateTest/CREATE_ContractRETURNBigOffset_d2g0v0.json",
    "GeneralStateTests/stCreateTest/CREATE_ContractRETURNBigOffset_d3g0v0.json",
    "GeneralStateTests/stCreateTest/CREATE_ContractSSTOREDuringInit_d0g0v0.json",
    "GeneralStateTests/stCreateTest/CREATE_ContractSuicideDuringInit_ThenStoreThenReturn_d0g0v0.json",
    "GeneralStateTests/stCreateTest/CREATE_ContractSuicideDuringInit_WithValueToItself_d0g0v0.json",
    "GeneralStateTests/stCreateTest/CREATE_ContractSuicideDuringInit_WithValue_d0g0v0.json",
    "GeneralStateTests/stCreateTest/CREATE_ContractSuicideDuringInit_d0g0v0.json",
    "GeneralStateTests/stCreateTest/CREATE_EContractCreateEContractInInit_Tr_d0g0v0.json",
    "GeneralStateTests/stCreateTest/CREATE_EContractCreateNEContractInInitOOG_Tr_d0g0v0.json",
    "GeneralStateTests/stCreateTest/CREATE_EContractCreateNEContractInInit_Tr_d0g0v0.json",
    "GeneralStateTests/stCreateTest/CREATE_EContract_ThenCALLToNonExistentAcc_d0g0v0.json",
    "GeneralStateTests/stCreateTest/CREATE_EmptyContractAndCallIt_0wei_d0g0v0.json",
    "GeneralStateTests/stCreateTest/CREATE_EmptyContractAndCallIt_1wei_d0g0v0.json",
    "GeneralStateTests/stCreateTest/CREATE_EmptyContractWithBalance_d0g0v0.json",
    "GeneralStateTests/stCreateTest/CREATE_EmptyContractWithStorageAndCallIt_0wei_d0g0v0.json",
    "GeneralStateTests/stCreateTest/CREATE_EmptyContractWithStorageAndCallIt_1wei_d0g0v0.json",
    "GeneralStateTests/stCreateTest/CREATE_EmptyContractWithStorage_d0g0v0.json",
    "GeneralStateTests/stCreateTest/CREATE_EmptyContract_d0g0v0.json",
    "GeneralStateTests/stCreateTest/CREATE_empty000CreateinInitCode_Transaction_d0g0v0.json",
    "GeneralStateTests/stCreateTest/CreateCollisionToEmpty_d0g0v0.json",
    "GeneralStateTests/stCreateTest/CreateCollisionToEmpty_d0g0v1.json",
    "GeneralStateTests/stCreateTest/TransactionCollisionToEmptyButCode_d0g0v0.json",
    "GeneralStateTests/stCreateTest/TransactionCollisionToEmptyButCode_d0g0v1.json",
    "GeneralStateTests/stCreateTest/TransactionCollisionToEmptyButNonce_d0g0v0.json",
    "GeneralStateTests/stCreateTest/TransactionCollisionToEmptyButNonce_d0g0v1.json",
    "GeneralStateTests/stCreateTest/TransactionCollisionToEmpty_d0g0v0.json",
    "GeneralStateTests/stCreateTest/TransactionCollisionToEmpty_d0g0v1.json",
    "GeneralStateTests/stDelegatecallTestHomestead/CallcodeLoseGasOOG_d0g0v0.json",
    "GeneralStateTests/stDelegatecallTestHomestead/callcodeWithHighValueAndGasOOG_d0g0v0.json",
    "GeneralStateTests/stEIP150singleCodeGasPrices/RawCallCodeGas_d0g0v0.json",
    "GeneralStateTests/stExample/add11_d0g0v0.json",
    "GeneralStateTests/stInitCodeTest/CallContractToCreateContractAndCallItOOG_d0g0v0.json",
    "GeneralStateTests/stInitCodeTest/CallContractToCreateContractNoCash_d0g0v0.json",
    "GeneralStateTests/stInitCodeTest/CallContractToCreateContractOOGBonusGas_d0g0v0.json",
    "GeneralStateTests/stInitCodeTest/CallContractToCreateContractOOG_d0g0v0.json",
    "GeneralStateTests/stInitCodeTest/CallContractToCreateContractWhichWouldCreateContractIfCalled_d0g0v0.json",
    "GeneralStateTests/stInitCodeTest/CallContractToCreateContractWhichWouldCreateContractInInitCode_d0g0v0.json",
    "GeneralStateTests/stInitCodeTest/CallRecursiveContract_d0g0v0.json",
    "GeneralStateTests/stInitCodeTest/CallTheContractToCreateEmptyContract_d0g0v0.json",
    "GeneralStateTests/stInitCodeTest/NotEnoughCashContractCreation_d0g0v0.json",
    "GeneralStateTests/stInitCodeTest/OutOfGasContractCreation_d0g0v0.json",
    "GeneralStateTests/stInitCodeTest/OutOfGasPrefundedContractCreation_d0g0v0.json",
    "GeneralStateTests/stInitCodeTest/ReturnTest2_d0g0v0.json",
    "GeneralStateTests/stInitCodeTest/ReturnTest_d0g0v0.json",
    "GeneralStateTests/stInitCodeTest/StackUnderFlowContractCreation_d0g0v0.json",
    "GeneralStateTests/stInitCodeTest/TransactionCreateAutoSuicideContract_d0g0v0.json",
    "GeneralStateTests/stInitCodeTest/TransactionCreateRandomInitCode_d0g0v0.json",
    "GeneralStateTests/stInitCodeTest/TransactionCreateStopInInitcode_d0g0v0.json",
    "GeneralStateTests/stInitCodeTest/TransactionCreateSuicideInInitcode_d0g0v0.json",
    "GeneralStateTests/stLogTests/log0_emptyMem_d0g0v0.json",
    "GeneralStateTests/stLogTests/log0_logMemStartTooHigh_d0g0v0.json",
    "GeneralStateTests/stLogTests/log0_logMemsizeTooHigh_d0g0v0.json",
    "GeneralStateTests/stLogTests/log0_logMemsizeZero_d0g0v0.json",
    "GeneralStateTests/stLogTests/log0_nonEmptyMem_d0g0v0.json",
    "GeneralStateTests/stLogTests/log0_nonEmptyMem_logMemSize1_d0g0v0.json",
    "GeneralStateTests/stLogTests/log0_nonEmptyMem_logMemSize1_logMemStart31_d0g0v0.json",
    "GeneralStateTests/stLogTests/log1_Caller_d0g0v0.json",
    "GeneralStateTests/stLogTests/log1_MaxTopic_d0g0v0.json",
    "GeneralStateTests/stLogTests/log1_emptyMem_d0g0v0.json",
    "GeneralStateTests/stLogTests/log1_logMemStartTooHigh_d0g0v0.json",
    "GeneralStateTests/stLogTests/log1_logMemsizeTooHigh_d0g0v0.json",
    "GeneralStateTests/stLogTests/log1_logMemsizeZero_d0g0v0.json",
    "GeneralStateTests/stLogTests/log1_nonEmptyMem_d0g0v0.json",
    "GeneralStateTests/stLogTests/log1_nonEmptyMem_logMemSize1_d0g0v0.json",
    "GeneralStateTests/stLogTests/log1_nonEmptyMem_logMemSize1_logMemStart31_d0g0v0.json",
    "GeneralStateTests/stLogTests/log2_Caller_d0g0v0.json",
    "GeneralStateTests/stLogTests/log2_MaxTopic_d0g0v0.json",
    "GeneralStateTests/stLogTests/log2_emptyMem_d0g0v0.json",
    "GeneralStateTests/stLogTests/log2_logMemStartTooHigh_d0g0v0.json",
    "GeneralStateTests/stLogTests/log2_logMemsizeTooHigh_d0g0v0.json",
    "GeneralStateTests/stLogTests/log2_logMemsizeZero_d0g0v0.json",
    "GeneralStateTests/stLogTests/log2_nonEmptyMem_d0g0v0.json",
    "GeneralStateTests/stLogTests/log2_nonEmptyMem_logMemSize1_d0g0v0.json",
    "GeneralStateTests/stLogTests/log2_nonEmptyMem_logMemSize1_logMemStart31_d0g0v0.json",
    "GeneralStateTests/stLogTests/log3_Caller_d0g0v0.json",
    "GeneralStateTests/stLogTests/log3_MaxTopic_d0g0v0.json",
    "GeneralStateTests/stLogTests/log3_PC_d0g0v0.json",
    "GeneralStateTests/stLogTests/log3_emptyMem_d0g0v0.json",
    "GeneralStateTests/stLogTests/log3_logMemStartTooHigh_d0g0v0.json",
    "GeneralStateTests/stLogTests/log3_logMemsizeTooHigh_d0g0v0.json",
    "GeneralStateTests/stLogTests/log3_logMemsizeZero_d0g0v0.json",
    "GeneralStateTests/stLogTests/log3_nonEmptyMem_d0g0v0.json",
    "GeneralStateTests/stLogTests/log3_nonEmptyMem_logMemSize1_d0g0v0.json",
    "GeneralStateTests/stLogTests/log3_nonEmptyMem_logMemSize1_logMemStart31_d0g0v0.json",
    "GeneralStateTests/stLogTests/log4_Caller_d0g0v0.json",
    "GeneralStateTests/stLogTests/log4_MaxTopic_d0g0v0.json",
    "GeneralStateTests/stLogTests/log4_PC_d0g0v0.json",
    "GeneralStateTests/stLogTests/log4_emptyMem_d0g0v0.json",
    "GeneralStateTests/stLogTests/log4_logMemStartTooHigh_d0g0v0.json",
    "GeneralStateTests/stLogTests/log4_logMemsizeTooHigh_d0g0v0.json",
    "GeneralStateTests/stLogTests/log4_logMemsizeZero_d0g0v0.json",
    "GeneralStateTests/stLogTests/log4_nonEmptyMem_d0g0v0.json",
    "GeneralStateTests/stLogTests/log4_nonEmptyMem_logMemSize1_d0g0v0.json",
    "GeneralStateTests/stLogTests/log4_nonEmptyMem_logMemSize1_logMemStart31_d0g0v0.json",
    "GeneralStateTests/stLogTests/logInOOG_Call_d0g0v0.json",
    "GeneralStateTests/stMemExpandingEIP150Calls/CallAndCallcodeConsumeMoreGasThenTransactionHasWithMemExpandingCalls_d0g0v0.json",
    "GeneralStateTests/stMemExpandingEIP150Calls/CallAskMoreGasOnDepth2ThenTransactionHasWithMemExpandingCalls_d0g0v0.json",
    "GeneralStateTests/stMemExpandingEIP150Calls/CallGoesOOGOnSecondLevel2WithMemExpandingCalls_d0g0v0.json",
    "GeneralStateTests/stMemExpandingEIP150Calls/CallGoesOOGOnSecondLevelWithMemExpandingCalls_d0g0v0.json",
    "GeneralStateTests/stMemExpandingEIP150Calls/CreateAndGasInsideCreateWithMemExpandingCalls_d0g0v0.json",
    "GeneralStateTests/stMemExpandingEIP150Calls/ExecuteCallThatAskMoreGasThenTransactionHasWithMemExpandingCalls_d0g0v0.json",
    "GeneralStateTests/stMemExpandingEIP150Calls/NewGasPriceForCodesWithMemExpandingCalls_d0g0v0.json",
    "GeneralStateTests/stMemoryStressTest/FillStack_d0g0v0.json",
    "GeneralStateTests/stMemoryStressTest/FillStack_d0g1v0.json",
    "GeneralStateTests/stMemoryStressTest/RETURN_Bounds_d0g0v0.json",
    "GeneralStateTests/stMemoryStressTest/RETURN_Bounds_d0g1v0.json",
    "GeneralStateTests/stMemoryStressTest/RETURN_Bounds_d0g2v0.json",
    "GeneralStateTests/stMemoryStressTest/mload32bitBound2_d0g0v0.json",
    "GeneralStateTests/stMemoryStressTest/mload32bitBound2_d0g1v0.json",
    "GeneralStateTests/stMemoryStressTest/mload32bitBound_return2_d0g0v0.json",
    "GeneralStateTests/stMemoryStressTest/mload32bitBound_return2_d0g1v0.json",
    "GeneralStateTests/stMemoryStressTest/mload32bitBound_return_d0g0v0.json",
    "GeneralStateTests/stMemoryStressTest/mload32bitBound_return_d0g1v0.json",
    "GeneralStateTests/stMemoryTest/callDataCopyOffset_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/calldatacopy_dejavu2_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/calldatacopy_dejavu_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/codeCopyOffset_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/codecopy_dejavu2_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/codecopy_dejavu_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/extcodecopy_dejavu_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/log1_dejavu_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/log2_dejavu_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/log3_dejavu_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/log4_dejavu_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem0b_singleByte_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem31b_singleByte_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem32b_singleByte_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem32kb+1_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem32kb+31_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem32kb+32_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem32kb+33_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem32kb-1_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem32kb-31_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem32kb-32_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem32kb-33_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem32kb_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem32kb_singleByte+1_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem32kb_singleByte+31_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem32kb_singleByte+32_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem32kb_singleByte+33_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem32kb_singleByte-1_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem32kb_singleByte-31_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem32kb_singleByte-32_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem32kb_singleByte-33_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem32kb_singleByte_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem33b_singleByte_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem64kb+1_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem64kb+31_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem64kb+32_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem64kb+33_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem64kb-1_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem64kb-31_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem64kb-32_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem64kb-33_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem64kb_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem64kb_singleByte+1_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem64kb_singleByte+31_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem64kb_singleByte+32_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem64kb_singleByte+33_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem64kb_singleByte-1_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem64kb_singleByte-31_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem64kb_singleByte-32_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem64kb_singleByte-33_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mem64kb_singleByte_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/memReturn_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mload16bitBound_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mload8bitBound_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mload_dejavu_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mstore_dejavu_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/mstroe8_dejavu_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/sha3_dejavu_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/stackLimitGas_1023_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/stackLimitGas_1024_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/stackLimitGas_1025_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/stackLimitPush31_1023_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/stackLimitPush31_1024_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/stackLimitPush31_1025_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/stackLimitPush32_1023_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/stackLimitPush32_1024_d0g0v0.json",
    "GeneralStateTests/stMemoryTest/stackLimitPush32_1025_d0g0v0.json",
    "GeneralStateTests/stNonZeroCallsTest/NonZeroValue_CALLCODE_ToEmpty_d0g0v0.json",
    "GeneralStateTests/stNonZeroCallsTest/NonZeroValue_CALLCODE_ToNonNonZeroBalance_d0g0v0.json",
    "GeneralStateTests/stNonZeroCallsTest/NonZeroValue_CALLCODE_ToOneStorageKey_d0g0v0.json",
    "GeneralStateTests/stNonZeroCallsTest/NonZeroValue_CALLCODE_d0g0v0.json",
    "GeneralStateTests/stNonZeroCallsTest/NonZeroValue_CALL_ToEmpty_d0g0v0.json",
    "GeneralStateTests/stNonZeroCallsTest/NonZeroValue_CALL_ToNonNonZeroBalance_d0g0v0.json",
    "GeneralStateTests/stNonZeroCallsTest/NonZeroValue_CALL_ToOneStorageKey_d0g0v0.json",
    "GeneralStateTests/stNonZeroCallsTest/NonZeroValue_CALL_d0g0v0.json",
    "GeneralStateTests/stNonZeroCallsTest/NonZeroValue_DELEGATECALL_ToEmpty_d0g0v0.json",
    "GeneralStateTests/stNonZeroCallsTest/NonZeroValue_DELEGATECALL_ToNonNonZeroBalance_d0g0v0.json",
    "GeneralStateTests/stNonZeroCallsTest/NonZeroValue_DELEGATECALL_ToOneStorageKey_d0g0v0.json",
    "GeneralStateTests/stNonZeroCallsTest/NonZeroValue_DELEGATECALL_d0g0v0.json",
    "GeneralStateTests/stNonZeroCallsTest/NonZeroValue_SUICIDE_ToEmpty_d0g0v0.json",
    "GeneralStateTests/stNonZeroCallsTest/NonZeroValue_SUICIDE_ToNonNonZeroBalance_d0g0v0.json",
    "GeneralStateTests/stNonZeroCallsTest/NonZeroValue_SUICIDE_ToOneStorageKey_d0g0v0.json",
    "GeneralStateTests/stNonZeroCallsTest/NonZeroValue_SUICIDE_d0g0v0.json",
    "GeneralStateTests/stNonZeroCallsTest/NonZeroValue_TransactionCALL_ToEmpty_d0g0v0.json",
    "GeneralStateTests/stNonZeroCallsTest/NonZeroValue_TransactionCALL_ToNonNonZeroBalance_d0g0v0.json",
    "GeneralStateTests/stNonZeroCallsTest/NonZeroValue_TransactionCALL_ToOneStorageKey_d0g0v0.json",
    "GeneralStateTests/stNonZeroCallsTest/NonZeroValue_TransactionCALL_d0g0v0.json",
    "GeneralStateTests/stNonZeroCallsTest/NonZeroValue_TransactionCALLwithData_ToEmpty_d0g0v0.json",
    "GeneralStateTests/stNonZeroCallsTest/NonZeroValue_TransactionCALLwithData_ToNonNonZeroBalance_d0g0v0.json",
    "GeneralStateTests/stNonZeroCallsTest/NonZeroValue_TransactionCALLwithData_ToOneStorageKey_d0g0v0.json",
    "GeneralStateTests/stNonZeroCallsTest/NonZeroValue_TransactionCALLwithData_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODEEcrecover0_0input_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODEEcrecover0_Gas2999_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODEEcrecover0_NoGas_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODEEcrecover0_completeReturnValue_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODEEcrecover0_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODEEcrecover0_gas3000_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODEEcrecover0_overlappingInputOutput_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODEEcrecover1_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODEEcrecover2_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODEEcrecover3_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODEEcrecover80_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODEEcrecoverH_prefixed0_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODEEcrecoverR_prefixed0_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODEEcrecoverS_prefixed0_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODEEcrecoverV_prefixed0_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODEEcrecoverV_prefixedf0_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODEEcrecoverV_prefixedf0_d1g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODEIdentitiy_0_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODEIdentitiy_1_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODEIdentity_1_nonzeroValue_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODEIdentity_2_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODEIdentity_3_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODEIdentity_4_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODEIdentity_4_gas17_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODEIdentity_4_gas18_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODEIdentity_5_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODERipemd160_0_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODERipemd160_1_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODERipemd160_2_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODERipemd160_3_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODERipemd160_3_postfixed0_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODERipemd160_3_prefixed0_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODERipemd160_4_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODERipemd160_4_gas719_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODERipemd160_5_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODESha256_0_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODESha256_1_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODESha256_1_nonzeroValue_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODESha256_2_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODESha256_3_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODESha256_3_postfix0_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODESha256_3_prefix0_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODESha256_4_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODESha256_4_gas99_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CALLCODESha256_5_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallEcrecover0_0input_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallEcrecover0_Gas2999_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallEcrecover0_NoGas_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallEcrecover0_completeReturnValue_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallEcrecover0_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallEcrecover0_gas3000_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallEcrecover0_overlappingInputOutput_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallEcrecover1_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallEcrecover2_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallEcrecover3_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallEcrecover80_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallEcrecoverCheckLengthWrongV_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallEcrecoverCheckLength_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallEcrecoverH_prefixed0_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallEcrecoverR_prefixed0_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallEcrecoverS_prefixed0_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallEcrecoverV_prefixed0_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallIdentitiy_0_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallIdentitiy_1_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallIdentity_1_nonzeroValue_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallIdentity_2_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallIdentity_3_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallIdentity_4_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallIdentity_4_gas17_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallIdentity_4_gas18_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallIdentity_5_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallRipemd160_0_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallRipemd160_1_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallRipemd160_2_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallRipemd160_3_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallRipemd160_3_postfixed0_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallRipemd160_3_prefixed0_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallRipemd160_4_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallRipemd160_4_gas719_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallRipemd160_5_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallSha256_0_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallSha256_1_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallSha256_1_nonzeroValue_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallSha256_2_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallSha256_3_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallSha256_3_postfix0_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallSha256_3_prefix0_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallSha256_4_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallSha256_4_gas99_d0g0v0.json",
    "GeneralStateTests/stPreCompiledContracts2/CallSha256_5_d0g0v0.json",
    "GeneralStateTests/stRandom2/201503110226PYTHON_DUP6_d0g0v0.json",
    "GeneralStateTests/stRefundTest/refund50_1_d0g0v0.json",
    "GeneralStateTests/stRefundTest/refund50_2_d0g0v0.json",
    "GeneralStateTests/stRefundTest/refund50percentCap_d0g0v0.json",
    "GeneralStateTests/stRefundTest/refund600_d0g0v0.json",
    "GeneralStateTests/stRefundTest/refundSuicide50procentCap_d0g0v0.json",
    "GeneralStateTests/stRefundTest/refund_CallA_OOG_d0g0v0.json",
    "GeneralStateTests/stRefundTest/refund_CallA_d0g0v0.json",
    "GeneralStateTests/stRefundTest/refund_CallA_notEnoughGasInCall_d0g0v0.json",
    "GeneralStateTests/stRefundTest/refund_CallToSuicideNoStorage_d0g0v0.json",
    "GeneralStateTests/stRefundTest/refund_CallToSuicideStorage_d0g0v0.json",
    "GeneralStateTests/stRefundTest/refund_CallToSuicideTwice_d0g0v0.json",
    "GeneralStateTests/stRefundTest/refund_NoOOG_1_d0g0v0.json",
    "GeneralStateTests/stRefundTest/refund_OOG_d0g0v0.json",
    "GeneralStateTests/stRefundTest/refund_TxToSuicideOOG_d0g0v0.json",
    "GeneralStateTests/stRefundTest/refund_TxToSuicide_d0g0v0.json",
    "GeneralStateTests/stRefundTest/refund_changeNonZeroStorage_d0g0v0.json",
    "GeneralStateTests/stRefundTest/refund_getEtherBack_d0g0v0.json",
    "GeneralStateTests/stRefundTest/refund_multimpleSuicide_d0g0v0.json",
    "GeneralStateTests/stRefundTest/refund_singleSuicide_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/call_ecrec_success_empty_then_returndatasize_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/call_outsize_then_create_successful_then_returndatasize_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/call_then_call_value_fail_then_returndatasize_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/call_then_create_successful_then_returndatasize_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/create_callprecompile_returndatasize_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/modexp_modsize0_returndatasize_d0g1v0.json",
    "GeneralStateTests/stReturnDataTest/modexp_modsize0_returndatasize_d0g2v0.json",
    "GeneralStateTests/stReturnDataTest/modexp_modsize0_returndatasize_d0g3v0.json",
    "GeneralStateTests/stReturnDataTest/returndatacopy_0_0_following_successful_create_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatacopy_after_failing_callcode_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatacopy_after_failing_delegatecall_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatacopy_after_failing_staticcall_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatacopy_after_revert_in_staticcall_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatacopy_after_successful_callcode_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatacopy_after_successful_delegatecall_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatacopy_after_successful_staticcall_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatacopy_following_call_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatacopy_following_create_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatacopy_following_failing_call_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatacopy_following_revert_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatacopy_following_revert_in_create_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatacopy_following_successful_create_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatacopy_following_too_big_transfer_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatacopy_initial_256_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatacopy_initial_256_d1g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatacopy_initial_256_d2g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatacopy_initial_big_sum_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatacopy_initial_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatacopy_overrun_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatasize_after_failing_callcode_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatasize_after_failing_staticcall_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatasize_after_oog_after_deeper_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatasize_after_successful_callcode_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatasize_after_successful_delegatecall_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatasize_after_successful_staticcall_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatasize_bug_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatasize_following_successful_create_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatasize_initial_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatasize_initial_zero_read_d0g0v0.json",
    "GeneralStateTests/stReturnDataTest/returndatasize_initial_zero_read_d1g0v0.json",
    "GeneralStateTests/stRevertTest/LoopCallsDepthThenRevert_d0g0v0.json",
    "GeneralStateTests/stRevertTest/LoopCallsThenRevert_d0g1v0.json",
    "GeneralStateTests/stRevertTest/LoopDelegateCallsDepthThenRevert_d0g0v0.json",
    "GeneralStateTests/stRevertTest/NashatyrevSuicideRevert_d0g0v0.json",
    "GeneralStateTests/stRevertTest/RevertDepthCreateAddressCollision_d1g0v0.json",
    "GeneralStateTests/stRevertTest/RevertDepthCreateAddressCollision_d1g0v1.json",
    "GeneralStateTests/stRevertTest/RevertDepthCreateOOG_d0g0v0.json",
    "GeneralStateTests/stRevertTest/RevertDepthCreateOOG_d0g0v1.json",
    "GeneralStateTests/stRevertTest/RevertDepthCreateOOG_d1g0v0.json",
    "GeneralStateTests/stRevertTest/RevertDepthCreateOOG_d1g0v1.json",
    "GeneralStateTests/stRevertTest/RevertDepthCreateOOG_d1g1v0.json",
    "GeneralStateTests/stRevertTest/RevertDepthCreateOOG_d1g1v1.json",
    "GeneralStateTests/stRevertTest/RevertInCallCode_d0g0v0.json",
    "GeneralStateTests/stRevertTest/RevertInCreateInInit_d0g0v0.json",
    "GeneralStateTests/stRevertTest/RevertInDelegateCall_d0g0v0.json",
    "GeneralStateTests/stRevertTest/RevertOnEmptyStack_d0g0v0.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeCreate_d0g0v0.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeCreate_d0g1v0.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeDirectCall_d0g0v0.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeDirectCall_d0g1v0.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeInCallsOnNonEmptyReturnData_d0g0v0.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeInCallsOnNonEmptyReturnData_d0g1v0.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeInCreateReturns_d0g0v0.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeInInit_d0g0v0.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeInInit_d0g0v1.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeInInit_d0g1v0.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeInInit_d0g1v1.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeMultipleSubCalls_d0g0v0.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeMultipleSubCalls_d0g0v1.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeReturn_d0g0v0.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeReturn_d0g1v0.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeReturn_d1g0v0.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeReturn_d1g1v0.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeReturn_d2g0v0.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeReturn_d2g1v0.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeReturn_d3g0v0.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeReturn_d3g1v0.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeReturn_d4g0v0.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeReturn_d4g1v0.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeReturn_d5g0v0.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeReturn_d5g1v0.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeWithBigOutputInInit_d0g0v0.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeWithBigOutputInInit_d0g0v1.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeWithBigOutputInInit_d0g1v0.json",
    "GeneralStateTests/stRevertTest/RevertOpcodeWithBigOutputInInit_d0g1v1.json",
    "GeneralStateTests/stRevertTest/RevertOpcode_d0g0v0.json",
    "GeneralStateTests/stRevertTest/RevertOpcode_d0g0v1.json",
    "GeneralStateTests/stRevertTest/RevertOpcode_d0g1v0.json",
    "GeneralStateTests/stRevertTest/RevertOpcode_d0g1v1.json",
    "GeneralStateTests/stRevertTest/RevertPrefoundCall_d0g0v0.json",
    "GeneralStateTests/stRevertTest/RevertPrefoundEmptyCall_d0g0v0.json",
    "GeneralStateTests/stRevertTest/RevertPrefoundEmpty_d0g0v0.json",
    "GeneralStateTests/stRevertTest/RevertPrefound_d0g0v0.json",
    "GeneralStateTests/stRevertTest/RevertRemoteSubCallStorageOOG2_d0g0v0.json",
    "GeneralStateTests/stRevertTest/RevertRemoteSubCallStorageOOG_d0g0v0.json",
    "GeneralStateTests/stShift/sar01_d0g0v0.json",
    "GeneralStateTests/stShift/sar10_d0g0v0.json",
    "GeneralStateTests/stShift/sar11_d0g0v0.json",
    "GeneralStateTests/stShift/sar_2^254_254_d0g0v0.json",
    "GeneralStateTests/stShift/sar_2^255-1_248_d0g0v0.json",
    "GeneralStateTests/stShift/sar_2^255-1_254_d0g0v0.json",
    "GeneralStateTests/stShift/sar_2^255-1_255_d0g0v0.json",
    "GeneralStateTests/stShift/sar_2^255-1_256_d0g0v0.json",
    "GeneralStateTests/stShift/sar_2^255_1_d0g0v0.json",
    "GeneralStateTests/stShift/sar_2^255_255_d0g0v0.json",
    "GeneralStateTests/stShift/sar_2^255_256_d0g0v0.json",
    "GeneralStateTests/stShift/sar_2^255_257_d0g0v0.json",
    "GeneralStateTests/stShift/sar_2^256-1_0_d0g0v0.json",
    "GeneralStateTests/stShift/sar_2^256-1_1_d0g0v0.json",
    "GeneralStateTests/stShift/sar_2^256-1_255_d0g0v0.json",
    "GeneralStateTests/stShift/sar_2^256-1_256_d0g0v0.json",
    "GeneralStateTests/stShift/shl01-0100_d0g0v0.json",
    "GeneralStateTests/stShift/shl01-0101_d0g0v0.json",
    "GeneralStateTests/stShift/shl01-ff_d0g0v0.json",
    "GeneralStateTests/stShift/shl01_d0g0v0.json",
    "GeneralStateTests/stShift/shl10_d0g0v0.json",
    "GeneralStateTests/stShift/shl11_d0g0v0.json",
    "GeneralStateTests/stShift/shl7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff-01_d0g0v0.json",
    "GeneralStateTests/stShift/shlffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff-00_d0g0v0.json",
    "GeneralStateTests/stShift/shlffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff-0100_d0g0v0.json",
    "GeneralStateTests/stShift/shlffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff-01_d0g0v0.json",
    "GeneralStateTests/stShift/shlffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff-ff_d0g0v0.json",
    "GeneralStateTests/stShift/shr01_d0g0v0.json",
    "GeneralStateTests/stShift/shr10_d0g0v0.json",
    "GeneralStateTests/stShift/shr11_d0g0v0.json",
    "GeneralStateTests/stShift/shr_-1_0_d0g0v0.json",
    "GeneralStateTests/stShift/shr_-1_1_d0g0v0.json",
    "GeneralStateTests/stShift/shr_-1_255_d0g0v0.json",
    "GeneralStateTests/stShift/shr_-1_256_d0g0v0.json",
    "GeneralStateTests/stShift/shr_2^255_1_d0g0v0.json",
    "GeneralStateTests/stShift/shr_2^255_255_d0g0v0.json",
    "GeneralStateTests/stShift/shr_2^255_256_d0g0v0.json",
    "GeneralStateTests/stShift/shr_2^255_257_d0g0v0.json",
    "GeneralStateTests/stSolidityTest/CreateContractFromMethod_d0g0v0.json",
    "GeneralStateTests/stSolidityTest/RecursiveCreateContractsCreate4Contracts_d0g0v0.json",
    "GeneralStateTests/stSolidityTest/RecursiveCreateContracts_d0g0v0.json",
    "GeneralStateTests/stSpecialTest/FailedCreateRevertsDeletion_d0g0v0.json",
    "GeneralStateTests/stSpecialTest/StackDepthLimitSEC_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/ABAcalls0_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/ABAcalls1_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/ABAcalls2_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/ABAcalls3_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/ABAcallsSuicide0_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/ABAcallsSuicide1_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/Call10_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/CallRecursiveBomb0_OOG_atMaxCallDepth_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/CallRecursiveBomb0_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/CallRecursiveBomb1_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/CallRecursiveBomb2_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/CallRecursiveBomb3_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/CallRecursiveBombLog2_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/CallRecursiveBombLog_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/CallToNameRegistrator0_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/CallToNameRegistratorAddressTooBigLeft_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/CallToNameRegistratorAddressTooBigRight_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/CallToNameRegistratorMemOOGAndInsufficientBalance_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/CallToNameRegistratorNotMuchMemory0_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/CallToNameRegistratorNotMuchMemory1_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/CallToNameRegistratorOutOfGas_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/CallToNameRegistratorTooMuchMemory0_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/CallToNameRegistratorTooMuchMemory1_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/CallToNameRegistratorTooMuchMemory2_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/CallToNameRegistratorZeorSizeMemExpansion_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/CallToReturn1ForDynamicJump0_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/CallToReturn1ForDynamicJump1_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/CallToReturn1_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/CalltoReturn2_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/CreateHashCollision_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/PostToReturn1_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/TestNameRegistrator_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/balanceInputAddressTooBig_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/callValue_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/callcodeTo0_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/callcodeToNameRegistrator0_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/callcodeToNameRegistratorAddresTooBigLeft_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/callcodeToNameRegistratorAddresTooBigRight_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/callcodeToNameRegistratorZeroMemExpanion_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/callcodeToReturn1_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/callerAccountBalance_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/createNameRegistratorOOG_MemExpansionOOV_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/createNameRegistratorOutOfMemoryBonds0_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/createNameRegistratorOutOfMemoryBonds1_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/createNameRegistratorValueTooHigh_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/createNameRegistratorZeroMem2_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/createNameRegistratorZeroMemExpansion_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/createNameRegistratorZeroMem_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/createNameRegistrator_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/createWithInvalidOpcode_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/currentAccountBalance_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/doubleSelfdestructTest2_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/doubleSelfdestructTest_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/extcodecopy_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/return0_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/return1_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/return2_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/suicideAddress_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/suicideCallerAddresTooBigLeft_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/suicideCallerAddresTooBigRight_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/suicideCaller_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/suicideCoinbase_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/suicideNotExistingAccount_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/suicideOrigin_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/suicideSendEtherPostDeath_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/suicideSendEtherToMe_d0g0v0.json",
    "GeneralStateTests/stSystemOperationsTest/testRandomTest_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/ContractStoreClearsOOG_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/ContractStoreClearsSuccess_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/CreateMessageReverted_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/CreateMessageSuccess_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/CreateTransactionReverted_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/CreateTransactionSuccess_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/EmptyTransaction2_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/EmptyTransaction3_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/EmptyTransaction_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/HighGasLimit_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/InternalCallHittingGasLimit2_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/InternalCallHittingGasLimitSuccess_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/InternalCallHittingGasLimit_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/InternlCallStoreClearsOOG_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/InternlCallStoreClearsSucces_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d100g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d101g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d102g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d103g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d104g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d105g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d106g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d107g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d108g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d109g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d10g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d110g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d111g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d112g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d113g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d114g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d115g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d116g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d117g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d118g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d119g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d11g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d120g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d121g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d122g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d123g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d124g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d125g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d126g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d12g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d13g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d14g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d15g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d16g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d17g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d18g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d19g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d1g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d20g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d21g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d22g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d23g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d24g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d25g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d26g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d27g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d28g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d29g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d2g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d30g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d31g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d32g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d34g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d35g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d36g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d37g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d38g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d39g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d3g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d40g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d41g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d42g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d43g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d44g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d45g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d46g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d47g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d48g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d49g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d4g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d50g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d51g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d52g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d53g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d54g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d55g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d56g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d57g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d58g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d59g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d5g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d60g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d61g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d62g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d63g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d64g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d65g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d66g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d67g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d68g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d69g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d6g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d70g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d71g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d72g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d73g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d74g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d75g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d76g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d77g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d78g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d79g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d7g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d80g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d81g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d82g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d83g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d84g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d85g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d86g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d87g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d88g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d89g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d8g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d90g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d91g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d92g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d93g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d94g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d95g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d96g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d97g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d98g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d99g0v0.json",
    "GeneralStateTests/stTransactionTest/Opcodes_TransactionInit_d9g0v0.json",
    "GeneralStateTests/stTransactionTest/OverflowGasRequire2_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/OverflowGasRequire_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/RefundOverflow2_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/RefundOverflow_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/StoreClearsAndInternlCallStoreClearsOOG_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/StoreClearsAndInternlCallStoreClearsSuccess_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/StoreGasOnCreate_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/SuicidesAndInternlCallSuicidesBonusGasAtCallFailed_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/SuicidesAndInternlCallSuicidesBonusGasAtCall_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/SuicidesAndInternlCallSuicidesOOG_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/SuicidesAndInternlCallSuicidesSuccess_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/SuicidesAndInternlCallSuicidesSuccess_d1g0v0.json",
    "GeneralStateTests/stTransactionTest/SuicidesAndSendMoneyToItselfEtherDestroyed_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/SuicidesMixingCoinbase_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/SuicidesStopAfterSuicide_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/TransactionDataCosts652_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/TransactionFromCoinbaseHittingBlockGasLimit1_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/TransactionFromCoinbaseHittingBlockGasLimit_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/TransactionFromCoinbaseNotEnoughFounds_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/TransactionNonceCheck2_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/TransactionNonceCheck_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/TransactionSendingToEmpty_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/TransactionSendingToZero_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/TransactionToAddressh160minusOne_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/TransactionToItselfNotEnoughFounds_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/TransactionToItself_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/UserTransactionGasLimitIsTooLowWhenZeroCost_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/UserTransactionZeroCostWithData_d0g0v0.json",
    "GeneralStateTests/stTransactionTest/UserTransactionZeroCostWithData_d0g1v0.json",
    "GeneralStateTests/stTransactionTest/UserTransactionZeroCost_d0g0v0.json",
    "GeneralStateTests/stTransitionTest/createNameRegistratorPerTxsAfter_d0g0v0.json",
    "GeneralStateTests/stTransitionTest/createNameRegistratorPerTxsAt_d0g0v0.json",
    "GeneralStateTests/stTransitionTest/createNameRegistratorPerTxsBefore_d0g0v0.json",
    "GeneralStateTests/stTransitionTest/createNameRegistratorPerTxsNotEnoughGasAfter_d0g0v0.json",
    "GeneralStateTests/stTransitionTest/createNameRegistratorPerTxsNotEnoughGasAt_d0g0v0.json",
    "GeneralStateTests/stTransitionTest/createNameRegistratorPerTxsNotEnoughGasBefore_d0g0v0.json",
    "GeneralStateTests/stTransitionTest/delegatecallAfterTransition_d0g0v0.json",
    "GeneralStateTests/stTransitionTest/delegatecallAtTransition_d0g0v0.json",
    "GeneralStateTests/stTransitionTest/delegatecallBeforeTransition_d0g0v0.json",
    "GeneralStateTests/stWalletTest/dayLimitConstructionOOG_d0g0v0.json",
    "GeneralStateTests/stWalletTest/multiOwnedConstructionNotEnoughGasPartial_d0g0v0.json",
    "GeneralStateTests/stWalletTest/walletConstructionOOG_d0g0v0.json",
    "GeneralStateTests/stZeroCallsTest/ZeroValue_CALLCODE_ToEmpty_d0g0v0.json",
    "GeneralStateTests/stZeroCallsTest/ZeroValue_CALLCODE_ToNonZeroBalance_d0g0v0.json",
    "GeneralStateTests/stZeroCallsTest/ZeroValue_CALLCODE_ToOneStorageKey_d0g0v0.json",
    "GeneralStateTests/stZeroCallsTest/ZeroValue_CALLCODE_d0g0v0.json",
    "GeneralStateTests/stZeroCallsTest/ZeroValue_CALL_ToEmpty_d0g0v0.json",
    "GeneralStateTests/stZeroCallsTest/ZeroValue_CALL_ToNonZeroBalance_d0g0v0.json",
    "GeneralStateTests/stZeroCallsTest/ZeroValue_CALL_ToOneStorageKey_d0g0v0.json",
    "GeneralStateTests/stZeroCallsTest/ZeroValue_CALL_d0g0v0.json",
    "GeneralStateTests/stZeroCallsTest/ZeroValue_DELEGATECALL_ToEmpty_d0g0v0.json",
    "GeneralStateTests/stZeroCallsTest/ZeroValue_DELEGATECALL_ToNonZeroBalance_d0g0v0.json",
    "GeneralStateTests/stZeroCallsTest/ZeroValue_DELEGATECALL_ToOneStorageKey_d0g0v0.json",
    "GeneralStateTests/stZeroCallsTest/ZeroValue_DELEGATECALL_d0g0v0.json",
    "GeneralStateTests/stZeroCallsTest/ZeroValue_SUICIDE_ToEmpty_d0g0v0.json",
    "GeneralStateTests/stZeroCallsTest/ZeroValue_SUICIDE_ToNonZeroBalance_d0g0v0.json",
    "GeneralStateTests/stZeroCallsTest/ZeroValue_SUICIDE_ToOneStorageKey_d0g0v0.json",
    "GeneralStateTests/stZeroCallsTest/ZeroValue_SUICIDE_d0g0v0.json",
    "GeneralStateTests/stZeroCallsTest/ZeroValue_TransactionCALL_ToEmpty_d0g0v0.json",
    "GeneralStateTests/stZeroCallsTest/ZeroValue_TransactionCALL_ToNonZeroBalance_d0g0v0.json",
    "GeneralStateTests/stZeroCallsTest/ZeroValue_TransactionCALL_ToOneStorageKey_d0g0v0.json",
    "GeneralStateTests/stZeroCallsTest/ZeroValue_TransactionCALL_d0g0v0.json",
    "GeneralStateTests/stZeroCallsTest/ZeroValue_TransactionCALLwithData_ToEmpty_d0g0v0.json",
    "GeneralStateTests/stZeroCallsTest/ZeroValue_TransactionCALLwithData_ToNonZeroBalance_d0g0v0.json",
    "GeneralStateTests/stZeroCallsTest/ZeroValue_TransactionCALLwithData_ToOneStorageKey_d0g0v0.json",
    "GeneralStateTests/stZeroCallsTest/ZeroValue_TransactionCALLwithData_d0g0v0.json",
    "GeneralStateTests/stZeroKnowledge/pointMulAdd_d0g0v0.json",
    "GeneralStateTests/stZeroKnowledge/pointMulAdd_d0g1v0.json",
    "GeneralStateTests/stZeroKnowledge/pointMulAdd_d0g2v0.json",
    "GeneralStateTests/stZeroKnowledge/pointMulAdd_d1g0v0.json",
    "GeneralStateTests/stZeroKnowledge/pointMulAdd_d1g1v0.json",
    "GeneralStateTests/stZeroKnowledge/pointMulAdd_d1g2v0.json",
    "GeneralStateTests/stZeroKnowledge/pointMulAdd_d2g0v0.json",
    "GeneralStateTests/stZeroKnowledge/pointMulAdd_d2g1v0.json",
    "GeneralStateTests/stZeroKnowledge/pointMulAdd_d2g2v0.json",
    "GeneralStateTests/stZeroKnowledge/pointMulAdd_d3g0v0.json",
    "GeneralStateTests/stZeroKnowledge/pointMulAdd_d3g1v0.json",
    "GeneralStateTests/stZeroKnowledge/pointMulAdd_d3g2v0.json",
    "GeneralStateTests/stZeroKnowledge/pointMulAdd_d4g0v0.json",
    "GeneralStateTests/stZeroKnowledge/pointMulAdd_d4g1v0.json",
    "GeneralStateTests/stZeroKnowledge/pointMulAdd_d4g2v0.json",
    "GeneralStateTests/stZeroKnowledge/pointMulAdd_d5g0v0.json",
    "GeneralStateTests/stZeroKnowledge/pointMulAdd_d5g1v0.json",
    "GeneralStateTests/stZeroKnowledge/pointMulAdd_d5g2v0.json",
    "GeneralStateTests/stZeroKnowledge/pointMulAdd_d6g0v0.json",
    "GeneralStateTests/stZeroKnowledge/pointMulAdd_d6g1v0.json",
    "GeneralStateTests/stZeroKnowledge/pointMulAdd_d6g2v0.json",
    "GeneralStateTests/stZeroKnowledge/pointMulAdd_d7g0v0.json",
    "GeneralStateTests/stZeroKnowledge/pointMulAdd_d7g1v0.json",
    "GeneralStateTests/stZeroKnowledge/pointMulAdd_d7g2v0.json",
    "GeneralStateTests/stZeroKnowledge/pointMulAdd_d8g0v0.json",
    "GeneralStateTests/stZeroKnowledge/pointMulAdd_d8g1v0.json",
    "GeneralStateTests/stZeroKnowledge/pointMulAdd_d8g2v0.json",
    "bcBlockGasLimitTest/BlockGasLimit2p63m1.json",
    "bcBlockGasLimitTest/GasUsedHigherThanBlockGasLimitButNotWithRefundsSuicideFirst.json",
    "bcBlockGasLimitTest/GasUsedHigherThanBlockGasLimitButNotWithRefundsSuicideLast.json",
    "bcBlockGasLimitTest/SuicideTransaction.json",
    "bcBlockGasLimitTest/TransactionGasHigherThanLimit2p63m1.json",
    "bcBlockGasLimitTest/TransactionGasHigherThanLimit2p63m1_2.json",
    "bcExploitTest/DelegateCallSpam.json",
    "bcExploitTest/ShanghaiLove.json",
    "bcExploitTest/StrangeContractCreation.json",
    "bcExploitTest/SuicideIssue.json",
    "bcForgedTest/bcForkBlockTest.json",
    "bcForgedTest/bcForkUncle.json",
    "bcForgedTest/bcInvalidRLPTest.json",
    "bcForkStressTest/AmIOnEIP150.json",
    # "bcForkStressTest/ForkStressTest.json",
    "bcGasPricerTest/RPC_API_Test.json",
    "bcGasPricerTest/highGasUsage.json",
    "bcGasPricerTest/notxs.json",
    "bcInvalidHeaderTest/DifferentExtraData1025.json",
    "bcInvalidHeaderTest/DifficultyIsZero.json",
    "bcInvalidHeaderTest/ExtraData1024.json",
    "bcInvalidHeaderTest/ExtraData33.json",
    "bcInvalidHeaderTest/GasLimitHigherThan2p63m1.json",
    "bcInvalidHeaderTest/GasLimitIsZero.json",
    "bcInvalidHeaderTest/log1_wrongBlockNumber.json",
    "bcInvalidHeaderTest/log1_wrongBloom.json",
    "bcInvalidHeaderTest/wrongCoinbase.json",
    "bcInvalidHeaderTest/wrongDifficulty.json",
    "bcInvalidHeaderTest/wrongGasLimit.json",
    "bcInvalidHeaderTest/wrongGasUsed.json",
    "bcInvalidHeaderTest/wrongMixHash.json",
    "bcInvalidHeaderTest/wrongNonce.json",
    "bcInvalidHeaderTest/wrongNumber.json",
    "bcInvalidHeaderTest/wrongParentHash.json",
    "bcInvalidHeaderTest/wrongParentHash2.json",
    "bcInvalidHeaderTest/wrongReceiptTrie.json",
    "bcInvalidHeaderTest/wrongStateRoot.json",
    "bcInvalidHeaderTest/wrongTimestamp.json",
    "bcInvalidHeaderTest/wrongTransactionsTrie.json",
    "bcInvalidHeaderTest/wrongUncleHash.json",
    "bcMultiChainTest/CallContractFromNotBestBlock.json",
    "bcMultiChainTest/ChainAtoChainB.json",
    "bcMultiChainTest/ChainAtoChainBCallContractFormA.json",
    "bcMultiChainTest/ChainAtoChainB_BlockHash.json",
    "bcMultiChainTest/ChainAtoChainB_blockorder1.json",
    # "bcMultiChainTest/ChainAtoChainB_blockorder2.json",
    "bcMultiChainTest/ChainAtoChainB_difficultyB.json",
    "bcMultiChainTest/ChainAtoChainBtoChainA.json",
    "bcMultiChainTest/ChainAtoChainBtoChainAtoChainB.json",
    "bcMultiChainTest/UncleFromSideChain.json",
    "bcRandomBlockhashTest/randomStatetest109BC.json",
    "bcRandomBlockhashTest/randomStatetest113BC.json",
    "bcRandomBlockhashTest/randomStatetest127BC.json",
    "bcRandomBlockhashTest/randomStatetest128BC.json",
    "bcRandomBlockhashTest/randomStatetest132BC.json",
    "bcRandomBlockhashTest/randomStatetest140BC.json",
    "bcRandomBlockhashTest/randomStatetest141BC.json",
    "bcRandomBlockhashTest/randomStatetest152BC.json",
    "bcRandomBlockhashTest/randomStatetest165BC.json",
    "bcRandomBlockhashTest/randomStatetest168BC.json",
    "bcRandomBlockhashTest/randomStatetest181BC.json",
    "bcRandomBlockhashTest/randomStatetest182BC.json",
    "bcRandomBlockhashTest/randomStatetest186BC.json",
    "bcRandomBlockhashTest/randomStatetest193BC.json",
    "bcRandomBlockhashTest/randomStatetest203BC.json",
    "bcRandomBlockhashTest/randomStatetest213BC.json",
    "bcRandomBlockhashTest/randomStatetest218BC.json",
    "bcRandomBlockhashTest/randomStatetest21BC.json",
    "bcRandomBlockhashTest/randomStatetest224BC.json",
    "bcRandomBlockhashTest/randomStatetest234BC.json",
    "bcRandomBlockhashTest/randomStatetest235BC.json",
    "bcRandomBlockhashTest/randomStatetest239BC.json",
    "bcRandomBlockhashTest/randomStatetest240BC.json",
    "bcRandomBlockhashTest/randomStatetest253BC.json",
    "bcRandomBlockhashTest/randomStatetest255BC.json",
    "bcRandomBlockhashTest/randomStatetest256BC.json",
    "bcRandomBlockhashTest/randomStatetest258BC.json",
    "bcRandomBlockhashTest/randomStatetest262BC.json",
    "bcRandomBlockhashTest/randomStatetest272BC.json",
    "bcRandomBlockhashTest/randomStatetest277BC.json",
    "bcRandomBlockhashTest/randomStatetest284BC.json",
    "bcRandomBlockhashTest/randomStatetest289BC.json",
    "bcRandomBlockhashTest/randomStatetest314BC.json",
    "bcRandomBlockhashTest/randomStatetest317BC.json",
    "bcRandomBlockhashTest/randomStatetest319BC.json",
    "bcRandomBlockhashTest/randomStatetest330BC.json",
    "bcRandomBlockhashTest/randomStatetest331BC.json",
    "bcRandomBlockhashTest/randomStatetest344BC.json",
    "bcRandomBlockhashTest/randomStatetest34BC.json",
    "bcRandomBlockhashTest/randomStatetest35BC.json",
    "bcRandomBlockhashTest/randomStatetest373BC.json",
    "bcRandomBlockhashTest/randomStatetest374BC.json",
    "bcRandomBlockhashTest/randomStatetest390BC.json",
    "bcRandomBlockhashTest/randomStatetest392BC.json",
    "bcRandomBlockhashTest/randomStatetest394BC.json",
    "bcRandomBlockhashTest/randomStatetest400BC.json",
    "bcRandomBlockhashTest/randomStatetest403BC.json",
    "bcRandomBlockhashTest/randomStatetest40BC.json",
    "bcRandomBlockhashTest/randomStatetest427BC.json",
    "bcRandomBlockhashTest/randomStatetest431BC.json",
    "bcRandomBlockhashTest/randomStatetest432BC.json",
    "bcRandomBlockhashTest/randomStatetest434BC.json",
    "bcRandomBlockhashTest/randomStatetest44BC.json",
    "bcRandomBlockhashTest/randomStatetest453BC.json",
    "bcRandomBlockhashTest/randomStatetest459BC.json",
    # "bcRandomBlockhashTest/randomStatetest463BC.json",
    "bcRandomBlockhashTest/randomStatetest479BC.json",
    "bcRandomBlockhashTest/randomStatetest486BC.json",
    "bcRandomBlockhashTest/randomStatetest490BC.json",
    "bcRandomBlockhashTest/randomStatetest492BC.json",
    "bcRandomBlockhashTest/randomStatetest515BC.json",
    "bcRandomBlockhashTest/randomStatetest522BC.json",
    "bcRandomBlockhashTest/randomStatetest529BC.json",
    "bcRandomBlockhashTest/randomStatetest530BC.json",
    "bcRandomBlockhashTest/randomStatetest540BC.json",
    "bcRandomBlockhashTest/randomStatetest551BC.json",
    "bcRandomBlockhashTest/randomStatetest557BC.json",
    "bcRandomBlockhashTest/randomStatetest561BC.json",
    "bcRandomBlockhashTest/randomStatetest568BC.json",
    # "bcRandomBlockhashTest/randomStatetest56BC.json",
    "bcRandomBlockhashTest/randomStatetest570BC.json",
    "bcRandomBlockhashTest/randomStatetest590BC.json",
    "bcRandomBlockhashTest/randomStatetest591BC.json",
    "bcRandomBlockhashTest/randomStatetest593BC.json",
    "bcRandomBlockhashTest/randomStatetest595BC.json",
    "bcRandomBlockhashTest/randomStatetest598BC.json",
    "bcRandomBlockhashTest/randomStatetest606BC.json",
    "bcRandomBlockhashTest/randomStatetest613BC.json",
    "bcRandomBlockhashTest/randomStatetest614BC.json",
    # "bcRandomBlockhashTest/randomStatetest617BC.json",
    "bcRandomBlockhashTest/randomStatetest61BC.json",
    "bcRandomBlockhashTest/randomStatetest622BC.json",
    "bcRandomBlockhashTest/randomStatetest623BC.json",
    "bcRandomBlockhashTest/randomStatetest631BC.json",
    "bcRandomBlockhashTest/randomStatetest634BC.json",
    "bcRandomBlockhashTest/randomStatetest65BC.json",
    "bcRandomBlockhashTest/randomStatetest68BC.json",
    "bcRandomBlockhashTest/randomStatetest70BC.json",
    "bcRandomBlockhashTest/randomStatetest71BC.json",
    "bcRandomBlockhashTest/randomStatetest76BC.json",
    "bcRandomBlockhashTest/randomStatetest79BC.json",
    "bcRandomBlockhashTest/randomStatetest86BC.json",
    "bcRandomBlockhashTest/randomStatetest8BC.json",
    "bcRandomBlockhashTest/randomStatetest91BC.json",
    "bcRandomBlockhashTest/randomStatetest93BC.json",
    "bcRandomBlockhashTest/randomStatetest99BC.json",
    "bcStateTests/BLOCKHASH_Bounds.json",
    "bcStateTests/BadStateRootTxBC.json",
    "bcStateTests/OOGStateCopyContainingDeletedContract.json",
    "bcStateTests/blockhashNonConstArg.json",
    "bcStateTests/blockhashTests.json",
    "bcStateTests/multimpleBalanceInstruction.json",
    "bcStateTests/simpleSuicide.json",
    "bcStateTests/suicideCoinbase.json",
    "bcStateTests/transactionFromNotExistingAccount.json",
    # "bcTotalDifficultyTest/lotsOfBranches.json",
    # "bcTotalDifficultyTest/lotsOfBranchesOverrideAtTheEnd.json",
    # "bcTotalDifficultyTest/lotsOfBranchesOverrideAtTheMiddle.json",
    "bcTotalDifficultyTest/lotsOfLeafs.json",
    # "bcTotalDifficultyTest/newChainFrom4Block.json",
    # "bcTotalDifficultyTest/newChainFrom5Block.json",
    "bcTotalDifficultyTest/newChainFrom6Block.json",
    # "bcTotalDifficultyTest/sideChainWithMoreTransactions.json",
    "bcTotalDifficultyTest/sideChainWithNewMaxDifficultyStartingFromBlock3AfterBlock4.json",
    "bcTotalDifficultyTest/uncleBlockAtBlock3AfterBlock3.json",
    "bcTotalDifficultyTest/uncleBlockAtBlock3afterBlock4.json",
    "bcUncleHeaderValidity/correct.json",
    "bcUncleHeaderValidity/diffTooHigh.json",
    "bcUncleHeaderValidity/diffTooLow.json",
    "bcUncleHeaderValidity/diffTooLow2.json",
    "bcUncleHeaderValidity/futureUncleTimestamp2.json",
    "bcUncleHeaderValidity/futureUncleTimestamp3.json",
    "bcUncleHeaderValidity/futureUncleTimestampDifficultyDrop.json",
    "bcUncleHeaderValidity/futureUncleTimestampDifficultyDrop2.json",
    "bcUncleHeaderValidity/gasLimitLTGasUsageUncle.json",
    "bcUncleHeaderValidity/gasLimitTooHigh.json",
    "bcUncleHeaderValidity/gasLimitTooHighExactBound.json",
    "bcUncleHeaderValidity/gasLimitTooLow.json",
    "bcUncleHeaderValidity/gasLimitTooLowExactBound.json",
    "bcUncleHeaderValidity/incorrectUncleNumber0.json",
    "bcUncleHeaderValidity/incorrectUncleNumber1.json",
    "bcUncleHeaderValidity/incorrectUncleNumber500.json",
    "bcUncleHeaderValidity/incorrectUncleTimestamp.json",
    "bcUncleHeaderValidity/incorrectUncleTimestamp2.json",
    "bcUncleHeaderValidity/nonceWrong.json",
    "bcUncleHeaderValidity/pastUncleTimestamp.json",
    "bcUncleHeaderValidity/timestampTooHigh.json",
    "bcUncleHeaderValidity/timestampTooLow.json",
    "bcUncleHeaderValidity/uncleBloomNot0.json",
    "bcUncleHeaderValidity/uncleBloomNot0_2.json",
    "bcUncleHeaderValidity/unknownUncleParentHash.json",
    "bcUncleHeaderValidity/wrongMixHash.json",
    "bcUncleHeaderValidity/wrongParentHash.json",
    "bcUncleHeaderValidity/wrongStateRoot.json",
    "bcUncleTest/EqualUncleInTwoDifferentBlocks.json",
    "bcUncleTest/InChainUncle.json",
    "bcUncleTest/InChainUncleFather.json",
    "bcUncleTest/InChainUncleGrandPa.json",
    "bcUncleTest/InChainUncleGreatGrandPa.json",
    "bcUncleTest/InChainUncleGreatGreatGrandPa.json",
    "bcUncleTest/InChainUncleGreatGreatGreatGrandPa.json",
    "bcUncleTest/InChainUncleGreatGreatGreatGreatGrandPa.json",
    "bcUncleTest/UncleIsBrother.json",
    "bcUncleTest/oneUncle.json",
    "bcUncleTest/oneUncleGeneration2.json",
    "bcUncleTest/oneUncleGeneration3.json",
    "bcUncleTest/oneUncleGeneration4.json",
    "bcUncleTest/oneUncleGeneration5.json",
    "bcUncleTest/oneUncleGeneration6.json",
    "bcUncleTest/oneUncleGeneration7.json",
    "bcUncleTest/threeUncle.json",
    "bcUncleTest/twoEqualUncle.json",
    "bcUncleTest/twoUncle.json",
    "bcUncleTest/uncleHeaderAtBlock2.json",
    "bcUncleTest/uncleHeaderAtBlock2Byzantium.json",
    "bcUncleTest/uncleHeaderWithGeneration0.json",
    "bcUncleTest/uncleWithSameBlockNumber.json",
    "bcValidBlockTest/ExtraData32.json",
    "bcValidBlockTest/RecallSuicidedContract.json",
    "bcValidBlockTest/RecallSuicidedContractInOneBlock.json",
    "bcValidBlockTest/SimpleTx.json",
    "bcValidBlockTest/SimpleTx3.json",
    "bcValidBlockTest/SimpleTx3LowS.json",
    "bcValidBlockTest/callRevert.json",
    "bcValidBlockTest/createRevert.json",
    "bcValidBlockTest/dataTx.json",
    "bcValidBlockTest/dataTx2.json",
    "bcValidBlockTest/diff1024.json",
    "bcValidBlockTest/gasLimitTooHigh.json",
    "bcValidBlockTest/gasLimitTooHigh2.json",
    "bcValidBlockTest/gasPrice0.json",
    "bcValidBlockTest/log1_correct.json",
    "bcValidBlockTest/timeDiff0.json",
    "bcValidBlockTest/timeDiff12.json",
    "bcValidBlockTest/timeDiff13.json",
    "bcValidBlockTest/timeDiff14.json",
    "bcValidBlockTest/txEqualValue.json",
    "bcValidBlockTest/txOrder.json",
    "bcWalletTest/wallet2outOf3txs.json",
    "bcWalletTest/wallet2outOf3txs2.json",
    "bcWalletTest/wallet2outOf3txsRevoke.json",
    "bcWalletTest/wallet2outOf3txsRevokeAndConfirmAgain.json",
    "bcWalletTest/walletReorganizeOwners.json"
  ]

  test "runs blockchain tests" do
    Enum.each(@tests, fn json_test_path ->
      json_test_path
      |> read_test()
      |> Enum.filter(fn {_name, test} ->
        test["network"] == "Frontier"
      end)
      |> Enum.map(fn {_name, test} -> test end)
      |> Enum.each(fn test ->
        run_test(test)
      end)
    end)
  end

  defp read_test(relative_path) do
    path = System.cwd() <> @ethereum_common_tests_path <> relative_path

    path
    |> File.read!()
    |> Poison.decode!()
  end

  defp run_test(json_test) do
    state = populate_prestate(json_test)
    chain = Blockchain.Chain.load_chain(:frontier_test)

    blocktree =
      create_blocktree()
      |> add_genesis_block(json_test, state, chain)
      |> add_blocks(json_test, state, chain)

    canonical_block = Blocktree.get_canonical_block(blocktree)
    best_block_hash = maybe_hex(json_test["lastblockhash"])

    assert canonical_block.block_hash == best_block_hash
  end

  defp add_genesis_block(blocktree, json_test, state, chain) do
    block =
      if json_test["genesisRLP"] do
        {:ok, block} = Blockchain.Block.decode_rlp(json_test["genesisRLP"])

        block
      end

    genesis_block = block_from_json(block, json_test["genesisBlockHeader"])

    {:ok, blocktree} =
      Blocktree.verify_and_add_block(
        blocktree,
        chain,
        genesis_block,
        state.db,
        false,
        maybe_hex(json_test["genesisBlockHeader"]["hash"])
      )

    blocktree
  end

  defp create_blocktree do
    Blocktree.new_tree()
  end

  defp add_blocks(blocktree, json_test, state, chain) do
    Enum.reduce(json_test["blocks"], blocktree, fn json_block, acc ->
      block = json_block["rlp"] |> Blockchain.Block.decode_rlp()

      case block do
        {:ok, block} ->
          block =
            block_from_json(
              block,
              json_block["blockHeader"],
              json_block["transactions"],
              json_block["uncleHeaders"]
            )

          case Blocktree.verify_and_add_block(acc, chain, block, state.db) do
            {:ok, blocktree} -> blocktree
            _ -> acc
          end

        _ ->
          acc
      end
    end)
  end

  defp block_from_json(block, json_header, json_transactions \\ [], json_ommers \\ []) do
    block = block || %Blockchain.Block{}
    header = header_from_json(json_header)
    transactions = transactions_from_json(json_transactions)
    ommers = ommers_from_json(json_ommers)

    %{block | header: header, transactions: transactions, ommers: ommers}
  end

  defp header_from_json(json_header) do
    %Header{
      parent_hash: maybe_hex(json_header["parentHash"]),
      ommers_hash: maybe_hex(json_header["uncleHash"]),
      beneficiary: maybe_hex(json_header["coinbase"]),
      state_root: maybe_hex(json_header["stateRoot"]),
      transactions_root: maybe_hex(json_header["transactionsTrie"]),
      receipts_root: maybe_hex(json_header["receiptTrie"]),
      logs_bloom: maybe_hex(json_header["bloom"]),
      difficulty: load_integer(json_header["difficulty"]),
      number: load_integer(json_header["number"]),
      gas_limit: load_integer(json_header["gasLimit"]),
      gas_used: load_integer(json_header["gasUsed"]),
      timestamp: load_integer(json_header["timestamp"]),
      extra_data: maybe_hex(json_header["extraData"]),
      mix_hash: maybe_hex(json_header["mixHash"]),
      nonce: maybe_hex(json_header["nonce"])
    }
  end

  defp ommers_from_json(json_ommers) do
    Enum.map(json_ommers || [], fn json_ommer ->
      %Header{
        parent_hash: maybe_hex(json_ommer["parentHash"]),
        ommers_hash: maybe_hex(json_ommer["uncleHash"]),
        beneficiary: maybe_hex(json_ommer["coinbase"]),
        state_root: maybe_hex(json_ommer["stateRoot"]),
        transactions_root: maybe_hex(json_ommer["transactionsTrie"]),
        receipts_root: maybe_hex(json_ommer["receiptTrie"]),
        logs_bloom: maybe_hex(json_ommer["bloom"]),
        difficulty: load_integer(json_ommer["difficulty"]),
        number: load_integer(json_ommer["number"]),
        gas_limit: load_integer(json_ommer["gasLimit"]),
        gas_used: load_integer(json_ommer["gasUsed"]),
        timestamp: load_integer(json_ommer["timestamp"]),
        extra_data: maybe_hex(json_ommer["extraData"]),
        mix_hash: maybe_hex(json_ommer["mixHash"]),
        nonce: maybe_hex(json_ommer["nonce"])
      }
    end)
  end

  defp transactions_from_json(json_transactions) do
    Enum.map(json_transactions || [], fn json_transaction ->
      init =
        if maybe_hex(json_transaction["to"]) == <<>> do
          maybe_hex(json_transaction["data"])
        else
          ""
        end

      %Transaction{
        nonce: load_integer(json_transaction["nonce"]),
        gas_price: load_integer(json_transaction["gasPrice"]),
        gas_limit: load_integer(json_transaction["gasLimit"]),
        to: maybe_hex(json_transaction["to"]),
        value: load_integer(json_transaction["value"]),
        v: load_integer(json_transaction["v"]),
        r: load_integer(json_transaction["r"]),
        s: load_integer(json_transaction["s"]),
        data: maybe_hex(json_transaction["data"]),
        init: init
      }
    end)
  end

  defp populate_prestate(json_test) do
    db = MerklePatriciaTree.Test.random_ets_db()

    state = %Trie{
      db: db,
      root_hash: maybe_hex(json_test["genesisBlockHeader"]["stateRoot"])
    }

    Enum.reduce(json_test["pre"], state, fn {address, account}, state ->
      storage = %Trie{
        root_hash: Trie.empty_trie_root_hash(),
        db: db
      }

      storage =
        Enum.reduce(account["storage"], storage, fn {key, value}, trie ->
          Storage.put(trie.db, trie.root_hash, load_integer(key), load_integer(value))
        end)

      new_account = %Account{
        nonce: load_integer(account["nonce"]),
        balance: load_integer(account["balance"]),
        storage_root: storage.root_hash
      }

      state
      |> Account.put_account(maybe_hex(address), new_account)
      |> Account.put_code(maybe_hex(address), maybe_hex(account["code"]))
    end)
  end
end
